[dev]
  port = 8888
  targetPort = 3001
  functions = "netlify/functions"
  
[build]
  command = "pnpm build"
  publish = ".next"

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"